// import guatemala from './guatemala.json'
// import guinea from './guinea.json'
// import iceland from './iceland.json'
// import guineaBissau from './guinea-bissau.json'
// import iran from './iran.json'
// import iraq from './iraq.json'
// import israel from './israel.json'
// import honduras from './honduras.json'
// import italy from './italy.json'
// import ivoryCost from './ivory-cost.json'
// import jamaica from './jamaica.json'
// import jordan from './jordan.json'
// import aze from './aze.json'
// import armenia from './armenia.json'
// import kuwait from './kuwait.json'
// import kazakhstan from './kazakhstan.json'
// import kyrgyzstan from './kyrgyzstan.json'
// import kosovo from './kosovo.json'
import laos from './laos.json'
import latvia from './latvia.json'
import lesotho from './lesotho.json'
import lebanon from './lebanon.json'

const data: any[] = [laos, latvia, lesotho, lebanon]

export default data
